# Generated by Django 2.1.8 on 2019-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='Seller/static/seller/images/default.jpg', upload_to='static/seller/images'),
        ),
    ]
