# Generated by Django 2.1.8 on 2019-09-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20190909_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32)),
                ('type_describe', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='seller/images/default.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods_type'),
        ),
    ]
