# Generated by Django 2.1.8 on 2019-09-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20190909_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_store',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_type',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='picture',
        ),
    ]
