# Generated by Django 2.1.8 on 2019-09-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_auto_20190909_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='', upload_to='seller/images'),
            preserve_default=False,
        ),
    ]
