# Generated by Django 2.1.8 on 2019-09-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_goods_goods_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods_type'),
        ),
    ]
