# Generated by Django 2.1.8 on 2019-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0010_goods_goods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_type',
            name='type_picture',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_pro_time',
            field=models.DateField(),
        ),
    ]
