# Generated by Django 2.1.8 on 2019-09-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190909_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
