# Generated by Django 2.1.8 on 2019-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190911_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
    ]
