# Generated by Django 2.1.8 on 2019-09-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_cartgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgoods',
            name='goods_status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
