# Generated by Django 2.1.8 on 2019-09-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_cartgoods_goods_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartgoods',
            old_name='goods_count',
            new_name='cart_user',
        ),
        migrations.RenameField(
            model_name='cartgoods',
            old_name='goods_status',
            new_name='goods_number',
        ),
        migrations.RenameField(
            model_name='cartgoods',
            old_name='goods_total_price',
            new_name='goods_total',
        ),
        migrations.RemoveField(
            model_name='cartgoods',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='cartgoods',
            name='store_id',
        ),
    ]
