# Generated by Django 2.1.8 on 2019-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0011_auto_20190916_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payorder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='gooods_status',
            field=models.IntegerField(default=0),
        ),
    ]
