# Generated by Django 2.1.8 on 2019-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0012_auto_20190919_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='gooods_status',
            new_name='order_status',
        ),
    ]
